### ISSUE TITLE
Tray positions wrong with multiple monitors setup

### ISSUE THREAD

**Issue by okonet** [jenslind/electron-positioner#11]
When using with multiple monitors, it seems that all `tray` positions aren't calculated properly.

Not sure if this is related to this package or `tray.getBounds()` in electron.

**Comment by okonet** [comment]
Seems like electron issue after all: https://github.com/electron/electron/issues/3500

**Comment by lalomartins** [comment]
Hi,

we recently encountered this in our app, and after a lot of debugging, we found the root cause (and way to reproduce) is pixel density / UI scaling / whatever MacOS calls it.  On Windows it's this thing (found in Display Settings):
![image](https://user-images.githubusercontent.com/1211455/111775702-bf9d0c80-88b9-11eb-868b-69538d332622.png)
Seems positioner is not taking this in consideration. So if you set your scale to 200%, and ask positioner for the bottom, it will position in the middle instead.

I don't know if you want to reopen this or open a new one. Either way, here's what we found, hope it helps.
